# Generated by Django 5.0.2 on 2025-06-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_online",
            field=models.BooleanField(default=False, verbose_name="Çevrimiçi mi?"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_seen",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Son görülme"
            ),
        ),
    ]
