# Generated by Django 5.0.2 on 2025-06-21 17:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_message_is_deleted"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatroom",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Sohbet Odası",
                "verbose_name_plural": "Sohbet Odaları",
            },
        ),
        migrations.AddField(
            model_name="chatroom",
            name="password",
            field=models.CharField(
                blank=True,
                help_text="Oda tipi 'Özel' ise bu alan zorunludur.",
                max_length=128,
                null=True,
                verbose_name="Oda Şifresi",
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="room_type",
            field=models.CharField(
                choices=[("public", "Herkese Açık"), ("private", "Özel (Şifreli)")],
                default="public",
                max_length=10,
                verbose_name="Oda Tipi",
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Güncellenme Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Oluşturulma Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Açıklama"),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="chat_rooms",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Üyeler",
            ),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Oda Adı"),
        ),
    ]
