# Generated by Django 5.0.2 on 2025-06-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_message_file_name_message_file_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="is_file_message",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
