# Generated by Django 5.0.2 on 2025-06-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_chatroom_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="banned_words",
            field=models.TextField(
                blank=True,
                help_text="Virgülle ayrılmış yasaklı kelimeler",
                null=True,
                verbose_name="Yasaklı Kelimeler",
            ),
        ),
    ]
